### ISSUE TITLE
Init Next.js App

### ISSUE THREAD

**Issue by casiimir** [casiimir/CB8-team-e#2]

**Comment by casiimir** [comment]
- Installare tutte le librerie e pacchetti utili
- Configurare il progetto su Github
- Creare la parte Backend - in congiunzione alla task MongoDB (/api)
- Testare con Postman le varie chiamate de BE
- Creare la pagina Homepage - e primi componenti utili

**Comment by Raukros00** [comment]
Creare lo schema dell'evento seguendo lo schema su discord.

Q:
- Bisogna inserire in User e Event un campo relativo all'immagine di profilo e a quella relativa all'evento.
